# Makefile for OPS exercise 
# Use tabs for indentation, not spaces!

all: printversion display

# Link object files and create a binary executable:
display: 
	gcc -Wall ex01.c -o ex01
	
# Compile C-file 

clean:
	rm -f ex01
	dir -als

printversion:
	gcc --version | grep gcc
